nelmio_cors:
  defaults:
    origin_regex: true
    allow_origin: ["%env(CORS_ALLOW_ORIGIN)%"]
    allow_methods: ["GET", "OPTIONS", "POST", "PUT", "PATCH", "DELETE"]
    allow_headers: ["Content-Type", "Authorization"]
    expose_headers: ["Link"]
    max_age: 3600
  paths:
    "^/api/": # Ограничить только маршрутами, начинающимися с /api/
      allow_origin: ["*"]
      allow_methods: ["GET", "OPTIONS", "POST", "PUT", "DELETE"]
      allow_headers: ["Content-Type", "Authorization"]
      expose_headers: ["Authorization"]
      max_age: 3600
