nelmio_cors:
  defaults:
    allow_origin: ["*"] # Или укажите конкретные домены, например, ['http://185.221.213.154:8080']
    allow_credentials: true
    allow_headers: ["Content-Type", "Authorization"]
    expose_headers: ["Authorization"]
    allow_methods: ["GET", "OPTIONS", "POST", "PUT", "DELETE"]
    max_age: 3600
  paths:
    "^/api/": # Настройки для всех API путей
      allow_origin: ["*"]
      allow_methods: ["POST", "GET", "OPTIONS"]
      allow_headers: ["Content-Type", "Authorization"]
      max_age: 3600
